version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Specify the Node.js version you need
    commands:
      - echo Installing source NPM packages...
      - npm install
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com)
  build:
    commands:
      - echo Build Docker image...
      - docker build -t <repository-name> .
      - docker tag <repository-name>:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<repository-name>:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<repository-name>:latest

artifacts:
  files:
    - '**/*'
